name: recipe_box
description: "Transform your personal recipe collection into a digital cookbook with this intuitive app, featuring interactive ingredient checklists and clear cooking instructions!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  image_picker: '>=1.1.2'
  flutter_animate: ^4.5.0
  material_symbols_icons: ^4.2858.1
  provider: ^6.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  logging: ^1.0.0
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.10
  mockito: ^5.0.0 

flutter:
  uses-material-design: true